### ISSUE TITLE
googlechrome FAIL: tests.browser.test_forms.test_textarea

### ISSUE THREAD

**Issue by keturn** [idealistdev/alfajor#2]
# 
## FAIL: tests.browser.test_forms.test_textarea

Traceback (most recent call last):  
  File "/home/kevint/v/alfaj/lib/python2.6/site-packages/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/kevint/src/alfajor/tests/browser/test_forms.py", line 176, in test_textarea
    assert data == [['ta', 'baz\r\nquux']]
AssertionError:
    <TextareaElement 24bb390 name='ta'>.enter('\x08\x08x')
    <alfajor._management.WebBrowser object at 0x1ff4550>.document.forms[0].submit(wait_for='page')
    [[u'ta', u'bazqux']] = loads(<alfajor._management.WebBrowser object at 0x1ff4550>.document['#data'].text_content)

> >  assert [[u'ta', u'bazqux']] == [['ta', 'baz\r\nquux']]

-------------------- >> begin captured logging << --------------------
tests.browser: INFO: open(/form/textareas)
tests.browser: DEBUG: selenium(open, ('http://localhost:8008/form/textareas', 'true'))
tests.browser: DEBUG: selenium(getHtmlSource, ())
tests.browser: DEBUG: selenium(submit, ('xpath=/html/body/form',))
tests.browser: DEBUG: selenium(waitForPageToLoad, (16000,))
tests.browser: DEBUG: selenium(getHtmlSource, ())
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', 'foo\r\nbar'))
tests.browser: DEBUG: selenium(submit, ('xpath=/html/body/form',))
tests.browser: DEBUG: selenium(waitForPageToLoad, (16000,))
tests.browser: DEBUG: selenium(getHtmlSource, ())
tests.browser: DEBUG: selenium(getValue, ('xpath=/html/body/form/textarea',))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'b'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', 'b'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'b'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'b'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'a'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', 'ba'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'a'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'a'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'z'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', 'baz'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'z'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'z'))
tests.browser: DEBUG: selenium(getHtmlSource, ())
tests.browser: DEBUG: selenium(getValue, ('xpath=/html/body/form/textarea',))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', '\13'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'baz'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', '\13'))

tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', '\13'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'q'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazq'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'q'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'q'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'u'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazqu'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'u'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'u'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'u'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazquu'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'u'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'u'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'X'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazquuX'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'X'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'X'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', '\13'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazquuX'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', '\13'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', '\13'))
tests.browser: DEBUG: selenium(getHtmlSource, ())
tests.browser: DEBUG: selenium(getValue, ('xpath=/html/body/form/textarea',))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', '\8'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazquu'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', '\8'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', '\8'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', '\8'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazqu'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', '\8'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', '\8'))
tests.browser: DEBUG: selenium(keyDown, ('xpath=/html/body/form/textarea', 'x'))
tests.browser: DEBUG: selenium(type, ('xpath=/html/body/form/textarea', u'bazqux'))
tests.browser: DEBUG: selenium(keyPress, ('xpath=/html/body/form/textarea', 'x'))
tests.browser: DEBUG: selenium(keyUp, ('xpath=/html/body/form/textarea', 'x'))
tests.browser: DEBUG: selenium(getHtmlSource, ())
tests.browser: DEBUG: selenium(submit, ('xpath=/html/body/form',))
tests.browser: DEBUG: selenium(waitForPageToLoad, (16000,))
tests.browser: DEBUG: selenium(getHtmlSource, ())
--------------------- >> end captured logging << ---------------------

**Comment by 7footmoustache** [comment]
Also fails using Safari browser
